dist: bionic
language: php

service:
  - docker

env:
  global:
    - DOCKER_TAG="$TRAVIS_TAG-$(date +%s)"

script:
  - make image

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY
  - docker tag kulturverein_wordpress $DOCKER_REGISTRY/$DOCKER_REPO:$DOCKER_TAG

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push $DOCKER_REGISTRY/$DOCKER_REPO:$DOCKER_TAG
    on:
      tags: true
