version: '3'

volumes:
  db_data:

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/wordpress
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - fpm
    ports:
      - 127.0.0.1:80:80

  fpm:
    build: .
    volumes:
      - .:/var/www/wordpress
    links:
      - "mysql:${DB_HOST}"

  wpcli:
    image: wordpress:cli
    volumes:
      - .:/var/www/html
    links:
      - "mysql:${DB_HOST}"
    depends_on:
      - mysql
      - fpm

  mysql:
    image: mariadb:10.3
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
