version: '3'

volumes:
  db_data:

services:
  wordpress:
    image: kulturverein_wordpress:latest
    build: .
    volumes: 
      - ./application:/var/www/application
      - ./vendor:/var/www/vendor
      - ./config:/var/www/config
    ports:
      - 127.0.0.1:80:80
    links:
      - mysql
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: mysql
      WP_ENV: development
      WP_HOME: http://kulturverein-petersburg.test
      WP_SITEURL: ${WP_HOME}/wp
      DOMAIN_CURRENT_SITE: kulturverein-petersburg.test
      AUTH_KEY: random_secret
      SECURE_AUTH_KEY: random_secret
      LOGGED_IN_KEY: random_secret
      NONCE_KEY: random_secret
      AUTH_SALT: random_secret
      SECURE_AUTH_SALT: random_secret
      LOGGED_IN_SALT: random_secret
      NONCE_SALT: random_secret

  mysql:
    image: mariadb:10.3
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: secret
